name: Build Modules
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Exécuter le script Bash
        run: |
          java -jar revanced-cli.jar -h
      - name: generate-patches
        run: |
          java -jar revanced-cli.jar options --path options.json --overwrite revanced-patches.jar
      - name: Build revanced
        run: |
          java -jar revanced-cli.jar patch youtube.apk -p -o youtube-19-30-36-revanced.apk -b revanced-patches.jar --options=options.json
      