name: Build ReVanced Extended
on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install and cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: /usr/local/bin
          key: ${{ runner.os }}-tools-pup-yq
          
      - name: Install tools if not cached
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          sudo unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/pup
          
      - id: set-matrix
        run: |
          APPS=$(yq e '.apps | keys | .[]' test.yaml | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=$APPS" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    name: Build ${{ matrix.app }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.prepare-matrix.outputs.apps) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup fetch script
        run: |
          chmod +x ./main.sh
          chmod +x ./script.sh
          chmod +x ./fetch_link.sh
          ls
      
      - name: Build app
        run: |
          ./main.sh ${{ matrix.app }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: revanced-${{ matrix.app }}-apk
          path: revanced-${{ matrix.app }}.apk
