name: Build Modules
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Download apk
        run: |
          wget https://dw.uptodown.net/dwn/Hm_lq1qmUkszJNaOTLaPd9-t2Otu-Nl9cMEdK3AsPgcd5ht-UQ-LfQQt-aNyPMZnTydBxjTmu7UOrI8HA0HxNKFecuOL9F3O7MeRkqg3c5uvaJjhdc1azyiMFZG7VeNR/FV8oxtBa4000aOpwrroqhCeEzvvKIgxXa8W2wc3ZLePHF2vHMraKtVV4nvX_vjCTD3PkythFONIIDeRlBu9OKyc7er_k-IzddaxgL_uZYcwMpkB2ZMrMLWf6yK-KaDNy/3nBS2s-WaRPdteac_NpLdQE1kCBjg0ThXEnwi_8ke9SMS3CIwucmVBb2WPEiNwKL6UEF2-gOh9RFN5IA2lyfkg==/youtube-19-30-36.apk
      - name: Exécuter le script Bash
        run: |
          java -jar revanced-cli.jar -h
      - name: generate-patches
        run: |
          java -jar revanced-cli.jar options --path options.json --overwrite revanced-patches.jar
      - name: Build revanced
        run: |
          java -jar revanced-cli.jar patch youtube-19-30-36.apk -p -o youtube-19-30-36-revanced.apk -b revanced-patches.jar --options=options.json
      