name: Build ReVanced Extended
on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install and cache tools
        id: cache-tools
        uses: actions/cache@v3
        with:
          path: ~/.local/bin
          key: ${{ runner.os }}-tools-pup-yq-v1
          
      - name: Install tools if not cached
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          wget -qO ~/.local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x ~/.local/bin/yq
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip -d ~/.local/bin
          chmod +x ~/.local/bin/pup
          
      - name: Add tools to PATH
        run: echo "~/.local/bin" >> $GITHUB_PATH
          
      - id: set-matrix
        run: |
          APPS=$(yq e '.apps | keys | .[]' test.yaml | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=$APPS" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    name: Build ${{ matrix.app }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.prepare-matrix.outputs.apps) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup fetch script
        run: |
          chmod +x ./main.sh
          chmod +x ./script.sh
          chmod +x ./fetch_link.sh
          ls
      
      - name: Build app
        run: |
          ./main.sh ${{ matrix.app }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: revanced-${{ matrix.app }}-apk
          path: revanced-${{ matrix.app }}.apk
