name: Build ReVanced Extended
on:
  workflow_dispatch:

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
      - name: Generate build matrix
        id: set-matrix
        run: |
          chmod +x ./fetch_app_from_file.sh
          matrix=$(./fetch_app_from_file.sh)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    needs: get-matrix
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix: ${{fromJson(needs.get-matrix.outputs.matrix)}}
    
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pup HTML parser
        run: |
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin
          
      - name: Setup fetch script
        run: |
          chmod +x ./main.sh
          chmod +x ./script.sh
          chmod +x ./fetch_link.sh
      
      - name: Build app
        run: |
          ./main.sh ${{ matrix.app }} ${{ matrix.patch }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: revanced-${{ matrix.app }}-${{ matrix.patch }}-apk
          path: revanced-${{ matrix.app }}-${{ matrix.patch }}.apk
