name: Build ReVanced Extended
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    permissions: write-all
    runs-on: ubuntu-latest
    
    steps:
      # Setup environment
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Prepare tools
      - name: Install pup HTML parser
        run: |
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin
          
      - name: Setup fetch script
        run: chmod +x ./main.sh
      
      - name: Download execute script
        run: |
          ./main.sh
      
      
      
      # Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: revanced-extended-apk
          path: revanced-extended.apk
