name: Build ReVanced Extended
on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          MATRIX=$(yq e '.apps | keys | {"app": .}' test.yaml | jq -s -c .)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    name: Build ${{ matrix.app }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pup HTML parser
        run: |
          wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin
          
      - name: Setup fetch script
        run: |
          chmod +x ./main.sh
          chmod +x ./script.sh
          chmod +x ./fetch_link.sh
          ls
      
      - name: Build app
        run: |
          ./main.sh ${{ matrix.app }} ${{ matrix.patch }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: revanced-${{ matrix.app }}-${{ matrix.patch }}-apk
          path: revanced-${{ matrix.app }}-${{ matrix.patch }}.apk
