name: Build Modules
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Grant execute permission for fetch_link.sh
        run: chmod +x ./fetch_link.sh
    
      - name: Fetch link
        run: |
          sudo wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          sudo unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin
          ./fetch_link.sh google-inc youtube 19.16.39 False universal
          ls
          
      - name: Download integrations
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/inotia00/revanced-integrations/releases/latest)
          DOWNLOAD_URL=$(echo $LATEST_RELEASE | jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url')
          wget $DOWNLOAD_URL -O revanced-integrations.apk
          
      - name: Exécuter le script Bash
        run: |
          java -jar revanced-cli-all.jar -h
      - name: generate-patches
        run: |
          java -jar revanced-cli-all.jar options --path options.json --overwrite revanced-patches.jar
      - name: Build revanced
        run: |
          java -jar revanced-cli-all.jar patch \
            -d device-name \
            -b revanced-patches.jar \
            -m revanced-integrations.apk \
            --options options.json \
            -p \
            -e "GmsCore support" \
            --mount \
            -o revanced-extended.apk \
            youtube-19.16.39.apk
      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: revanced-extended-apk
          path: revanced-extended.apk
