name: Build Modules
on:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Grant execute permission for fetch_link.sh
        run: chmod +x ./fetch_link.sh
    
      - name: Fetch link
        run: |
          sudo apt install pup wget
          ./fetch_link.sh google-inc youtube 19.15.36 false
      - name: Exécuter le script Bash
        run: |
          java -jar revanced-cli-all.jar -h
      - name: generate-patches
        run: |
          java -jar revanced-cli-all.jar options --path options.json --overwrite revanced-patches.jar
      - name: Build revanced
        run: |
          java -jar revanced-cli-all.jar patch \
            -d device-name \
            -b revanced-patches.jar \
            -m revanced-integrations.apk \
            --options options.json \
            -p \
            -e "GmsCore support" \
            --mount \
            -o revanced-extended.apk \
            youtube-19.15.36.apk
      